version: "3.8"
services:
  frontend:
    container_name: frontend
    build: ./taladpla-web
    ports:
      - "80:80"
      # - "4200:4200"
    depends_on:
      - backend

  backend:
    container_name: backend
    build: ./taladpla-app
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: Thesums@41
      POSTGRES_DB: taladpla
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
